### ISSUE TITLE
Incompatibilité Windows 10 1709 : Protocole SMB1 desactivé

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/se3-logonpy#1]
Plusieurs problèmes sont observés avec W10 1709 : 

C'est la conséquence de la desactivation du protocole smb1 : 
https://support.microsoft.com/en-ph/help/4034314/smbv1-is-not-installed-windows-10-and-windows-server-version-1709
**ATTENTION cette désactivation fait partie des mesures de sécurité contre Wannacry et autres. On est prévenus...**
 
solution : 

https://support.microsoft.com/en-us/help/2696547/how-to-enable-and-disable-smbv1-smbv2-and-smbv3-in-windows-and-windows-server

Tests effectués sur un vm wheezy à jour  branche se3XP, installation neuve W10 avec paquet samba-client-windows

- smbclient ne parvient pas à négocier une version du protocole smb: il faut forcer -mSMB2 ou 3, ou mettre client min protocol = SMB2 dans le smb.conf
- smbclient ne renvoie plus la signature de L'OS à la connexion. Il faut trouver un autre moyen de détecter la version
- problème avec les ACLS, smbcacls renvoie une erreur si on passe un utilisateur.
- les ACL sur les profiles posent à nouveau problème... En commentant toute modif faite par logonpyGPO.sh, cela semble passer !
- NTUSER.dat est redevenu ntuser.dat... sans commentaires !

**Comment by denis-b** [comment]
Ce bug reste à confirmer sur d'autres serveurs. Il n'est pas impossible qu'il soit lié à d'autres soucis de configuration du  se3

**Comment by denis-b** [comment]
Trois possiblilités pour la résolution : 
- activer l'accès au registre à distance (sc config remoteregistry start= auto), ce qui permet de récupérer des valeurs dans la BDR et de pousser des clés,
- mettre un témoin dans $admin avec la version
- passer en AD :-)

**Comment by lolo4992** [comment]
J'ai le même soucis sur mon se3 de prod.

**Comment by denis-b** [comment]
Attention le patch https://github.com/SambaEdu/se3-logonpy/commit/1ce1c306ae5ec8cd58258c4290f6e02c198abfba risque d'etre totalement incompatible avec W7 et les W10 antérieurs ! 
Uniquement destiné à tester...

**Comment by denis-b** [comment]
Testé sur du W10 1703 cela ne fonctionne pas tel quel. Problème d'acls sur le profile.  Il semble en plus que en 1709 ntuser.dat soit à nouveau en minuscules...

Pour smbclient, seul le protocole NT1 renvoie les infos de l'os. Or il est desactivé sur 1709.  Donc il faut faire autrement.

**Comment by denis-b** [comment]
Version correcte, qui ne cassera rien de l'existant
