### ISSUE TITLE
Utliser SMB2/3 pour les scripts de connexion

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/se3-logonpy#2]
Le mécanisme des GPO dépend de smbclient en version NT1. Ceci impose d'activer le serveur SMB1 sur les clients. Gros problème de sécurité. voir #1

Il est possible de passer smbclient en version SMB3.x, mais cela change pas mal de choses, et c'est probablement incompatible avec W7.

La seule solution réelle est de passer en AD...

**Comment by swirly** [comment]
Pour windows 7 en wheezy,  j'ai réussi à utiliser SMB2 pour les scripts de connexion en modifiant deux paramètres dans le SMB.conf
Le premier est le 
client min protocol = SMB2
le second, indispensable 
smb2 leases = yes

le smb2leases est marqué comme encore expérimental dans la version de samba sur wheezy, mais ça fonctionne sans accroc sur un réseau de prod en établissement, avec des PC, des macs et quelques linux.

**Comment by msuquet** [comment]
Le 22/12/2017 à 10:49, Laurent COOPER a écrit :
> Pour windows 7 en wheezy, j'ai réussi à utiliser SMB2 pour les scripts 
> de connexion en modifiant deux paramètres dans le SMB.conf
> Le premier est le
> client min protocol = SMB2
> le second, indispensable
> smb2 leases = yes
> 
> le smb2leases est marqué comme encore expérimental dans la version de 
> samba sur wheezy,
Ce n'est pas pour stretch ?

Cordialement,

-- 
Michel Suquet
Collège Jean-Monnet
http://www.clg-monnet-briis.ac-versailles.fr/

**Comment by swirly** [comment]
ça marche déjà pour la version wheezy (et ce ne doit plus être expérimental sur la version stretch)
J'ai un serveur stable en wheezy actuellement

**Comment by mollef** [comment]
A voir si c'est compatible avec les W10 qui sauf erreur utilisent smb1 en mode non AD....

**Comment by denis-b** [comment]
Résolution partielle par #7
