### ISSUE TITLE
permettre a logonpy de générer des "vraies" GPO

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/se3-logonpy#3]
Pour pouvoir conserver les configurations existantes en AD, il faut que logon.py puisse générer les fichiers GPO dans sysvol.

A priori le code actuel permet de faire ce qu'il faut, il faut juste ajouter le mécanisme permettant d'interagir avec AD pour l'enregistrement des GPO (samba-tool gpo ou modules python...)

**_logonpy n'a plus besoin d'être lancé au logon!_**

## Pour ecrire les GPO : 

- `samba-tool gpo create...` v créer le dossier {uuid} dans sysvol
- génerer les Registry.pol dans les dossiers User et Machine
- générer les scripts de logon, logoff, .lnk, et autres dans les dossiers User et Machine
- incrémenter le gpt.ini à la racine de la gpo

Aucune difficulté, c'est même bien plus simple que ce que l'on fait actuellement car cette génération est à faire uniquement lors de la modif de la config dans l'interface.

## Pour lire les GPO : 

Soit on conserve la representation actuelle en base de données sql, soit on lit les .pol en lien avec des fichiers de définition .admx 

## Configuration initiale : 
on convertit l'ensemble des groupes de clés se3 en  gpo, avec les .admx correspondants.  Il est peut-être possible de faire ceci en une seule fois depuis la console microsoft ? Ceci permettrait d'avoir une série de "GPO starter" sambaedu distribuées avec le paquet. **a tester**

## Configuration en production

Si les clés correspondent à un modèle .admx, elles sont affichées dans la console ms et peuvent être changées facilement.

# methode

**Comment by mollef** [comment]
N'a plus lieu d'être avec SE4/AD
